"""request participants

Revision ID: 0df3929cf291
Revises: 7c2d9ac550c3
Create Date: 2026-08-21 18:43:20.737931
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0df3929cf291'
down_revision: str | None = '7c2d9ac550c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_participants',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ACTIVE', 'DECLINED', 'LEFT', name='participation_status', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'staff_id', name='uq_participant_request_staff')
    )
    op.create_index(op.f('ix_request_participants_request_id'), 'request_participants', ['request_id'], unique=False)
    op.create_index(op.f('ix_request_participants_staff_id'), 'request_participants', ['staff_id'], unique=False)
    op.create_index(op.f('ix_request_participants_tenant_id'), 'request_participants', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_participants_tenant_id'), table_name='request_participants')
    op.drop_index(op.f('ix_request_participants_staff_id'), table_name='request_participants')
    op.drop_index(op.f('ix_request_participants_request_id'), table_name='request_participants')
    op.drop_table('request_participants')
    # ### end Alembic commands ###
