"""appointment reminders

Revision ID: bb17c5a3c503
Revises: 698264bdc129
Create Date: 2026-08-16 17:43:28.695829
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bb17c5a3c503'
down_revision: str | None = '698264bdc129'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reminded_day_before_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('reminded_same_day_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'reminded_same_day_at')
    op.drop_column('appointments', 'reminded_day_before_at')
    # ### end Alembic commands ###
