"""platform admin and tenant invites

Revision ID: f5ee9f75e6df
Revises: bb17c5a3c503
Create Date: 2026-08-16 18:34:12.331395
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f5ee9f75e6df'
down_revision: str | None = 'bb17c5a3c503'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admins',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)
    op.add_column('tenants', sa.Column('invite_token_hash', sa.String(length=64), nullable=True))
    op.add_column('tenants', sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('invite_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tenants_invite_token_hash'), 'tenants', ['invite_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_invite_token_hash'), table_name='tenants')
    op.drop_column('tenants', 'invite_accepted_at')
    op.drop_column('tenants', 'invite_expires_at')
    op.drop_column('tenants', 'invite_token_hash')
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.drop_table('platform_admins')
    # ### end Alembic commands ###
